//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class transectionError
    {
        public int transectionID { get; set; }
        public string transectionName { get; set; }
        public string screenName { get; set; }
        public string userName { get; set; }
    }
}
